%% Operation set case maker
% Code randomly permutates the operation set matrix generated by
% OperationSetGenerator to create different cases of operation order for
% subjects to perform during experimentation
clear; clc; close all
fdir = 'C:\Users\seboe\Documents\Grad School\Neuromechanics Lab\Dual Tasking\Cognitive Dual Task\Code\OperationSets\'; %save directory

load('Operation Set 24-Mar-2020.mat') %load operation set from OperationSetGenerator

%create random permutations for each case
Case1_perm = randperm(length(n_save));
Case2_perm = randperm(length(n_save));
Case3_perm = randperm(length(n_save));

%rearrange the operation sets for each case
n_Case1 = n_save(Case1_perm,:);
num_Case1 = num_save(Case1_perm,:);
ops_Case1 = ops_save(Case1_perm,:);

n_Case2 = n_save(Case2_perm,:);
num_Case2 = num_save(Case2_perm,:);
ops_Case2 = ops_save(Case2_perm,:);

n_Case3 = n_save(Case3_perm,:);
num_Case3 = num_save(Case3_perm,:);
ops_Case3 = ops_save(Case3_perm,:);

%save
save([fdir 'Case 1 Operation Set ' date],'n_Case1','num_Case1','ops_Case1')
save([fdir 'Case 2 Operation Set ' date],'n_Case2','num_Case2','ops_Case2')
save([fdir 'Case 3 Operation Set ' date],'n_Case3','num_Case3','ops_Case3')